# Set CRAN repository mirror
options(repos = c(CRAN = "https://cran.rstudio.com/"))

# Load required packages
install.packages("dplyr")
install.packages("plotly")
install.packages("htmlwidgets")  # Ensure htmlwidgets is installed

library(dplyr)
library(plotly)
library(htmlwidgets)  # Load htmlwidgets library

# Load your dataset (replace 'your_data.csv' with your actual file path)
data <- read.csv('big_data/analysis/data.csv')

# Group data by Product Type and SKU, summing the revenue generated
grouped_data <- data %>%
  group_by(`Product.Type`, SKU) %>%
  summarise(`Revenue.generated` = sum(`Revenue.generated`, na.rm = TRUE)) %>%
  ungroup()

# Create the line chart
revenue_chart <- plot_ly(
    data = grouped_data,
    x = ~SKU,
    y = ~`Revenue.generated`,
    color = ~`Product.Type`,
    type = 'scatter',
    mode = 'lines+markers',
    marker = list(size = 8)  # Optional: set marker size
) %>%
  layout(
    title = 'Revenue Generated by SKU Under Each Product Type',
    xaxis = list(title = 'SKU'),
    yaxis = list(title = 'Revenue Generated'),
    template = 'plotly_white'
  )

# Show the figure
revenue_chart

# Save the figure as an HTML file
saveWidget(revenue_chart, "REVENUE_SKU.html")
